### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by crissty** [ricco381/yii2-ticket#1]
Hi,
It is possible to translate the documentation in English or Spanish?
You could specify which files need to put the guidelines? And what routes will call in view of the module.

Thanks!

**Comment by ricco381** [comment]
Hi, the translation is not planned in the near future , sorry.
But the module itself easy to use .
The route will be set by you yourself in the router , for example '<controller: (ticket) / <action> =>' / ricco / ticket / <action>
There will be questions ask me luck .

**Comment by ricco381** [comment]
https://github.com/ricco381/yii2-ticket/blob/master/README_EN.md

**Comment by crissty** [comment]
Thank you very much , you've been very kind to translate the documentation .
Congratulations for your work , I 've been using and is quite stable and easy to understand.
I recommend it, thanks !

**Comment by ricco381** [comment]
Thanks I was trying!

**Comment by ricco381** [comment]
Update to version 1.0.7

**Comment by mtangoo** [comment]
Hello here.
Can someone guide me how to change module language to English?

**Comment by mtangoo** [comment]
Also I get error

>Cannot use object of type app\models\User as array

Is there a special configuration for user model? There is no mention in docs
