### ISSUE TITLE
Проблема миграции

### ISSUE THREAD

**Issue by andreypopov98** [ricco381/yii2-ticket#2]
Здравствуйте, при попытке миграции вылазит данная ошибка, не могу понять с чем она может быть связана, спасибо!

>  add foreign key fk_ticket_head: ticket_head (user_id) references user (id) ...Exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table 'rio.#sql-22e4_25' (errno: 150)
The SQL being executed was: ALTER TABLE `ticket_head` ADD CONSTRAINT `fk_ticket_head` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE'
in C:\Server\OpenServer\domains\rio.ru\vendor\yiisoft\yii2\db\Schema.php:636
Error Info:
Array
(
    [0] => HY000
    [1] => 1005
    [2] => Can't create table 'rio.#sql-22e4_25' (errno: 150)
)

**Comment by ricco381** [comment]
Здравствуйте, таблица "user" существует?

**Comment by andreypopov98** [comment]
Нет, а она не создается автоматически ?

**Comment by ricco381** [comment]
Нет, модуль писался под [https://github.com/dektrium/yii2-user](https://github.com/dektrium/yii2-user) но может работать и под стандартным, я надеюсь на это, сам я не проверял

**Comment by andreypopov98** [comment]
Спасибо!))  👍
